### ISSUE TITLE
LaTeX equations are rendered much smaller in PDF from xaringan slides, with partial_slides = TRUE

### ISSUE THREAD

**Issue by privefl** [jhelvy/xaringanBuilder#84]
E.g. these slides:
```
---
title: "test"
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: title-slide center middle inverse

# Title

---

### Slide 1 with formula $Q = 1 - P$

Formula is smaller here as well: $$Q = 1 - P$$
```

***

This is what I use to render the slides:
```r
chromote::local_chrome_version(binary = "chrome-headless-shell")
renderthis::to_pdf("test.Rmd", partial_slides = TRUE)
```
It seems fine when I don't use `partial_slides = TRUE`.
